### ISSUE TITLE
Automount not working in latest release.

### ISSUE THREAD

**Issue by dokatomi** [dianlight/hassio-addons#214]
### Addon

SambaNAS

### Description

Config not changed, but automount not working anymore.

### Reproduction steps

```bash
Update SambaNas to latest, and start it.
```

### Addon Logs

```bash
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-automount: starting
[08:56:33] INFO: Protection Mode is false
[08:56:33] INFO: MoreDisk or Automount option found!
---------------------------------------------------
Supported fs: 	ext3	ext2	ext4	squashfs	vfat	msdos	f2fs	fuseblk	ntfs3	exfat	btrfs	xfs
Supported fusefs: apfs  
---------------------------------------------------
[08:56:33] INFO: MediaLibrary disabled in config. Disk are mounted only for this addon!
---------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/disklist.py", line 15, in <module>
    plist = d.get_partition_list()
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/diskinfo/disk.py", line 825, in get_partition_list
    result.append(Partition(os.path.basename(path), _read_file(path + "/dev")))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/diskinfo/partition.py", line 116, in __init__
    self.__part_number = int(_read_udev_property(path, "ID_PART_ENTRY_NUMBER="))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
[08:56:33] INFO: No Disk with labels.
---------------------------------------------------
[08:56:33] INFO: MoreDisks to mount:

	sda1
[08:56:34] WARNING: Disk with label sda1 not found.
s6-rc: info: service init-automount successfully started
s6-rc: info: service init-smartd: starting
s6-rc: info: service init-samba: starting
s6-rc: info: service hd-idle: starting
s6-rc: info: service hd-idle successfully started
[08:56:34] INFO: Hostname: homeassistant
[08:56:34] INFO: Interfaces: wlan0 end0 
[08:56:34] INFO: Docker Interface: hassio 172.30.32.0/23
s6-rc: info: service init-smartd successfully started
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
Added user dokatomi.
---------------------------------------------------
[08:56:35] INFO: Exposed Disks Summary:
[CONFIG]                path = /homeassistant # TM:false#
[ADDONS]                path = /addons # TM:false#
[SSL]                   path = /ssl # TM:false#
[SHARE]                 path = /share # TM:false#
[BACKUP]                path = /backup # TM:false#
[MEDIA]                 path = /media # TM:false#
[ADDON_CONFIGS]         path = /addon_configs # TM:false#
---------------------------------------------------
s6-rc: info: service init-samba successfully started
s6-rc: info: service init-mqtt: starting
s6-rc: info: service wsdd: starting
s6-rc: info: service smbd: starting
s6-rc: info: service nmbd: starting
s6-rc: info: service avahi: starting
s6-rc: info: service wsdd successfully started
s6-rc: info: service nmbd successfully started
s6-rc: info: service smbd successfully started
s6-rc: info: service cifs-supervisor-mount: starting
s6-rc: info: service avahi successfully started
[08:56:35] INFO: Starting the wsdd daemon for WORKGROUP/homeassistant...
[08:56:35] INFO: Starting the AVAHI for homeassistant...
Waiting for daemon ...
s6-rc: info: service cifs-supervisor-mount successfully started
[08:56:35] INFO: MQTT support not enabled in config
s6-rc: info: service init-mqtt successfully started
s6-rc: info: service mqtt-disk-handler: starting
[08:56:35] INFO: Interfaces: -i wlan0 -i end0 
s6-rc: info: service mqtt-disk-handler successfully started
s6-rc: info: service mqtt-handler: starting
s6-rc: info: service mqtt-handler successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2024-02-21 08:56:36,193:wsdd INFO(pid 314): using pre-defined UUID cb6a33a0-b841-531d-a34e-09ecec492eb1
2024-02-21 08:56:36,197:wsdd INFO(pid 314): joined multicast group 239.255.255.250 on 10.0.10.200%end0
2024-02-21 08:56:36,205:wsdd INFO(pid 314): scheduling Hello message via end0 to 239.255.255.250%end0
2024-02-21 08:56:36,254:wsdd INFO(pid 314): joined multicast group [ff02::c] on fe80::8a2a:14e5:59e2:d670%end0
2024-02-21 08:56:36,257:wsdd INFO(pid 314): scheduling Hello message via end0 to ff02::c%end0
2024-02-21 08:56:36,300:wsdd INFO(pid 314): 10.0.10.50 - - "POST /cb6a33a0-b841-531d-a34e-09ecec492eb1 HTTP/1.1" 200 -
2024-02-21 08:56:36,415:wsdd INFO(pid 314): fe80::398e:e891:9158:ac7d - - "POST /cb6a33a0-b841-531d-a34e-09ecec492eb1 HTTP/1.1" 200 -
nmbd version 4.18.9 started.
smbd version 4.18.9 started.
Copyright Andrew Tridgell and the Samba Team 1992-2023
Copyright Andrew Tridgell and the Samba Team 1992-2023
INFO: Profiling support unavailable in this build.
*****

Samba name server HOMEASSISTANT is now a local master browser for workgroup WORKGROUP on subnet 172.30.32.1

*****
```

### Addon Config

```bash
workgroup: WORKGROUP
username: ***
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 169.254.0.0/16
  - fe80::/10
  - fc00::/7
automount: true
moredisks:
  - sda1
mountoptions:
  - nosuid
  - relatime
  - noexec
available_disks_log: true
medialibrary:
  enable: false
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false
recyle_bin_enabled: false
wsdd2: false
mqtt_nexgen_entities: false
autodiscovery: {}
other_users: []
acl: []
interfaces: []
password: ***
```

### Architecture

aarch64

### OS

HaOS

**Comment by dokatomi** [comment]
I tried with the name "usb-128gb" and it works. :)

Here are the USB Drive details:

DEVLINKS: >-
  /dev/disk/by-id/usb-SanDisk_Ultra_Fit_0101e41ac6ea5cc55739b5c1d9fc6acf330cf87d4673bd1e0458309a8b02487a61ba00000000000000000000f6aad8caff9f5100835581071f283014-0:0-part1
  /dev/disk/by-label/usb-128gb
  /dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1:1.0-scsi-0:0:0:0-part1
  /dev/disk/by-uuid/57ecb341-15ea-4a40-8ea4-6a8800e7ef7d
DEVNAME: /dev/sda1
DEVPATH: >-
  /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-1/2-1:1.0/host0/target0:0:0/0:0:0:0/block/sda/sda1
DEVTYPE: partition
DISKSEQ: '32'
ID_BUS: usb
ID_FS_LABEL: usb-128gb
ID_FS_LABEL_ENC: usb-128gb
ID_FS_TYPE: ext4
ID_FS_USAGE: filesystem
ID_FS_UUID: 57ecb341-15ea-4a40-8ea4-6a8800e7ef7d
ID_FS_UUID_ENC: 57ecb341-15ea-4a40-8ea4-6a8800e7ef7d
ID_FS_VERSION: '1.0'
ID_INSTANCE: '0:0'
ID_MODEL: Ultra_Fit
ID_MODEL_ENC: Ultra\x20Fit\x20\x20\x20\x20\x20\x20\x20
ID_MODEL_ID: '5583'
ID_PART_TABLE_TYPE: dos
ID_PART_TABLE_UUID: fe342046
ID_PATH: platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1:1.0-scsi-0:0:0:0
ID_PATH_TAG: platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_1_0-scsi-0_0_0_0
ID_REVISION: '1.00'
ID_SERIAL: >-
  SanDisk_Ultra_Fit_0101e41ac6ea5cc55739b5c1d9fc6acf330cf87d4673bd1e0458309a8b02487a61ba00000000000000000000f6aad8caff9f5100835581071f283014-0:0
ID_SERIAL_SHORT: >-
  0101e41ac6ea5cc55739b5c1d9fc6acf330cf87d4673bd1e0458309a8b02487a61ba00000000000000000000f6aad8caff9f5100835581071f283014
ID_TYPE: disk
ID_USB_DRIVER: usb-storage
ID_USB_INSTANCE: '0:0'
ID_USB_INTERFACES: ':080650:'
ID_USB_INTERFACE_NUM: '00'
ID_USB_MODEL: Ultra_Fit
ID_USB_MODEL_ENC: Ultra\x20Fit\x20\x20\x20\x20\x20\x20\x20
ID_USB_MODEL_ID: '5583'
ID_USB_REVISION: '1.00'
ID_USB_SERIAL: >-
  SanDisk_Ultra_Fit_0101e41ac6ea5cc55739b5c1d9fc6acf330cf87d4673bd1e0458309a8b02487a61ba00000000000000000000f6aad8caff9f5100835581071f283014-0:0
ID_USB_SERIAL_SHORT: >-
  0101e41ac6ea5cc55739b5c1d9fc6acf330cf87d4673bd1e0458309a8b02487a61ba00000000000000000000f6aad8caff9f5100835581071f283014
ID_USB_TYPE: disk
ID_USB_VENDOR: SanDisk
ID_USB_VENDOR_ENC: SanDisk\x20
ID_USB_VENDOR_ID: '0781'
ID_VENDOR: SanDisk
ID_VENDOR_ENC: SanDisk\x20
ID_VENDOR_ID: '0781'
MAJOR: '8'
MINOR: '1'
PARTN: '1'
SUBSYSTEM: block
TAGS: ':systemd:'
USEC_INITIALIZED: '1102464780808'
