### ISSUE TITLE
❓ [addon] Sambanas no write access to mounted drive

### ISSUE THREAD

**Issue by cristian19961** [dianlight/hassio-addons#253]
### Addon

SambaNAS

### Your request

Hi,

I cannot write to the mounted drive. Any ideas how I can fix it? I have the feeling it's a permission-issue.

Cheers!

**Comment by dianlight** [comment]
I can’t help you without a magic crystal :)
Please give me some information, your addon’s config and logs are a good start. 

L.

**Comment by cristian19961** [comment]
Hi,

Makes sense, sorry.

Config: workgroup: WORKGROUP
username: cristian
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 169.254.0.0/16
  - fe80::/10
  - fc00::/7
automount: true
moredisks:
  - USB
mountoptions: []
available_disks_log: true
medialibrary:
  enable: true
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false
recyle_bin_enabled: false
wsdd2: false
mqtt_nexgen_entities: false
autodiscovery: {}
other_users: []
acl: []
interfaces: []
password: ----
hdd_idle_seconds: 360
log_level: trace

Log:
change_to_user_impersonate: Skipping user change - already user
vfs_ChDir to /tmp
fsp_new: allocated files structure (2 used)
file_free: freed files structure 0 (1 used)
fsp_new: allocated files structure (2 used)
file_free: freed files structure 0 (1 used)
vfs_ChDir: vfs_ChDir got /tmp
fsp_new: allocated files structure (2 used)
file_free: freed files structure 0 (1 used)
fsp_new: allocated files structure (2 used)
file_free: freed files structure 0 (1 used)
print_impersonation_info: Impersonated user: uid=(65534,65534), gid=(0,65534), cwd=[/tmp]
np_write_send: len: 72
change_to_user_impersonate: Skipping user change - already user
fsp_new: allocated files structure (2 used)
file_free: freed files structure 0 (1 used)
fsp_new: allocated files structure (2 used)
file_free: freed files structure 0 (1 used)
print_impersonation_info: Impersonated user: uid=(65534,65534), gid=(0,65534), cwd=[/tmp]
np_write_send: len: 92
change_to_user_impersonate: Skipping user change - already user
fsp_new: allocated files structure (2 used)
file_free: freed files structure 0 (1 used)
fsp_new: allocated files structure (2 used)
file_free: freed files structure 0 (1 used)
print_impersonation_info: Impersonated user: uid=(65534,65534), gid=(0,65534), cwd=[/tmp]
dbwrap_lock_order_lock: check lock order 1 for /var/cache/samba/smbXsrv_open_global.tdb
dbwrap_lock_order_unlock: release lock order 1 for /var/cache/samba/smbXsrv_open_global.tdb
file_free: freed files structure 187721168 (0 used)
change_to_user_impersonate: Skipping user change - already user
fsp_new: allocated files structure (1 used)
file_free: freed files structure 0 (0 used)
fsp_new: allocated files structure (1 used)
file_free: freed files structure 0 (0 used)
print_impersonation_info: Impersonated user: uid=(65534,65534), gid=(0,65534), cwd=[/tmp]
setting sec ctx (0, 0) - sec_ctx_stack_ndx = 0
Security token: (NULL)
UNIX token of user 0
Primary group is 0 and contains 0 supplementary groups
change_to_root_user: now uid=(0,0) gid=(0,0)
setting sec ctx (0, 0) - sec_ctx_stack_ndx = 0
Security token: (NULL)
UNIX token of user 0
Primary group is 0 and contains 0 supplementary groups
change_to_root_user: now uid=(0,0) gid=(0,0)
vfs_ChDir to /tmp
fsp_new: allocated files structure (1 used)
file_free: freed files structure 0 (0 used)
fsp_new: allocated files structure (1 used)
file_free: freed files structure 0 (0 used)
vfs_ChDir: vfs_ChDir got /tmp
setting sec ctx (0, 0) - sec_ctx_stack_ndx = 0
Security token: (NULL)
UNIX token of user 0
Primary group is 0 and contains 0 supplementary groups
change_to_root_user: now uid=(0,0) gid=(0,0)
homeassistant (ipv4:127.0.0.1:54432) closed connection to service IPC$
vfs_ChDir to /
fsp_new: allocated files structure (1 used)
chdir_below_conn: Bad access attempt: . is a symlink outside the share path
conn_rootdir =/tmp
resolved_name=/
file_free: freed files structure 0 (0 used)
vfs_ChDir: vfs_ChDir got /
setting sec ctx (0, 0) - sec_ctx_stack_ndx = 0
Security token: (NULL)
UNIX token of user 0
Primary group is 0 and contains 0 supplementary groups
change_to_root_user: now uid=(0,0) gid=(0,0)
dbwrap_lock_order_lock: check lock order 1 for /var/cache/samba/smbXsrv_tcon_global.tdb
dbwrap_lock_order_unlock: release lock order 1 for /var/cache/samba/smbXsrv_tcon_global.tdb
dbwrap_lock_order_lock: check lock order 1 for /var/cache/samba/smbXsrv_client_global.tdb
dbwrap_lock_order_unlock: release lock order 1 for /var/cache/samba/smbXsrv_client_global.tdb
setting sec ctx (0, 0) - sec_ctx_stack_ndx = 0
Security token: (NULL)
UNIX token of user 0
Primary group is 0 and contains 0 supplementary groups
change_to_root_user: now uid=(0,0) gid=(0,0)
setting sec ctx (0, 0) - sec_ctx_stack_ndx = 0
Security token: (NULL)
UNIX token of user 0
Primary group is 0 and contains 0 supplementary groups
change_to_root_user: now uid=(0,0) gid=(0,0)
setting sec ctx (0, 0) - sec_ctx_stack_ndx = 0
Security token: (NULL)
UNIX token of user 0
Primary group is 0 and contains 0 supplementary groups
change_to_root_user: now uid=(0,0) gid=(0,0)
dbwrap_lock_order_lock: check lock order 1 for /var/cache/samba/smbXsrv_session_global.tdb
dbwrap_lock_order_unlock: release lock order 1 for /var/cache/samba/smbXsrv_session_global.tdb
setting sec ctx (0, 0) - sec_ctx_stack_ndx = 0
Security token: (NULL)
UNIX token of user 0
Primary group is 0 and contains 0 supplementary groups
change_to_root_user: now uid=(0,0) gid=(0,0)
setting sec ctx (0, 0) - sec_ctx_stack_ndx = 0
Security token: (NULL)
UNIX token of user 0
Primary group is 0 and contains 0 supplementary groups
change_to_root_user: now uid=(0,0) gid=(0,0)
Server exit (NT_STATUS_END_OF_FILE)

Hope you can help. I'm trying for 2 weeks now and it's gonna be frustrating.

Thanks!

**Comment by dianlight** [comment]
All seem correct, and I don't see any write or permission error.

What kind of drive is USB? An ssd an hd, mmc ? The format?

Remove trace log option and post the startup log one possibility is that is a fat or similarly (vfat16, vfat32, exfat) and is wrongly mount as ntfs.

L

**Comment by cristian19961** [comment]
Hi,

Thanks for your answer!
It's an 10TB hdd from Seagate. Format is ext4.
Is this the correct log?

s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Samba NAS
 Expose Home Assistant disc with SMB/CIFS
-----------------------------------------------------------
 Add-on version: 12.2.0-nas2
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.1  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.9.1
 Home Assistant Supervisor: 2024.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to ERROR
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-automount: starting
---------------------------------------------------
Supported fs: 	ext3	ext2	ext4	squashfs	vfat	msdos	f2fs	erofs	fuseblk	ntfs3	exfat	btrfs	xfs
Supported fusefs: apfs  
---------------------------------------------------
---------------------------------------------------
---------------------------------------------------
s6-rc: info: service init-automount successfully started
s6-rc: info: service init-smartd: starting
s6-rc: info: service init-samba: starting
s6-rc: info: service hd-idle: starting
s6-rc: info: service hd-idle successfully started
symlinkPolicy=0, defaultIdle=0, defaultCommand=scsi, defaultPowerCondition=0, debug=false, logFile=, devices=
smartctl 7.4 2023-08-01 r5530 [aarch64-linux-6.6.31-haos-raspi] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF ENABLE/DISABLE COMMANDS SECTION ===
SMART Enabled.
SMART Attribute Autosave Enabled.
SMART Automatic Timers not supported

SMART Automatic Offline Testing Enabled every four hours.

s6-rc: info: service init-smartd successfully started
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
Added user cristian.
Added user _ha_mount_user_.
---------------------------------------------------
---------------------------------------------------
s6-rc: info: service init-samba successfully started
s6-rc: info: service init-mqtt: starting
s6-rc: info: service wsdd: starting
s6-rc: info: service smbd: starting
s6-rc: info: service nmbd: starting
s6-rc: info: service avahi: starting
s6-rc: info: service wsdd successfully started
s6-rc: info: service nmbd successfully started
s6-rc: info: service avahi successfully started
s6-rc: info: service smbd successfully started
s6-rc: info: service cifs-supervisor-mount: starting
s6-rc: info: service init-mqtt successfully started
Waiting for daemon ...
2024-09-14 20:04:04,373:wsdd INFO(pid 343): using pre-defined UUID cb6a33a0-b841-531d-a34e-09ecec492eb1
2024-09-14 20:04:04,377:wsdd INFO(pid 343): joined multicast group 239.255.255.250 on 192.168.0.3%end0
2024-09-14 20:04:04,386:wsdd INFO(pid 343): scheduling Hello message via end0 to 239.255.255.250%end0
2024-09-14 20:04:04,410:wsdd INFO(pid 343): joined multicast group [ff02::c] on fe80::e424:4986:fc3:68de%end0
2024-09-14 20:04:04,411:wsdd INFO(pid 343): scheduling Hello message via end0 to ff02::c%end0
smbd version 4.18.9 started.
Copyright Andrew Tridgell and the Samba Team 1992-2023
nmbd version 4.18.9 started.
Copyright Andrew Tridgell and the Samba Team 1992-2023
INFO: Profiling support unavailable in this build.

No locked files
Samba version 4.18.9
PID     Username     Group        Machine                                   Protocol Version  Encryption           Signing              
----------------------------------------------------------------------------------------------------------------------------------------

Service      pid     Machine       Connected at                     Encryption   Signing     
---------------------------------------------------------------------------------------------


s6-rc: info: service cifs-supervisor-mount successfully started
s6-rc: info: service mqtt-disk-handler: starting
s6-rc: info: service mqtt-disk-handler successfully started
s6-rc: info: service mqtt-handler: starting
s6-rc: info: service mqtt-handler successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started

**Comment by cristian19961** [comment]
Add to my previous message:
I'm seeing this in my Supervisor-log:

2024-09-14 21:46:53.605 INFO (MainThread) [supervisor.hardware.monitor] Detecting remove hardware /dev/bsg/1:0:0:0 - None
2024-09-14 21:46:53.615 INFO (MainThread) [supervisor.hardware.monitor] Detecting remove hardware /dev/sdb1 - /dev/disk/by-id/ata-ST10000NM0046_ZA240NBA-part1
2024-09-14 21:46:53.622 INFO (MainThread) [supervisor.hardware.monitor] Detecting remove hardware /dev/sdb2 - /dev/disk/by-id/ata-ST10000NM0046_ZA240NBA-part2
2024-09-14 21:46:53.629 INFO (MainThread) [supervisor.hardware.monitor] Detecting remove hardware /dev/sdb - /dev/disk/by-id/ata-ST10000NM0046_ZA240NBA
2024-09-14 21:46:53.706 INFO (MainThread) [supervisor.hardware.monitor] Detecting remove hardware /dev/bus/usb/002/010 - None
2024-09-14 21:47:09.416 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1759' coro=<UDisks2Manager._interfaces_added() done, defined at /usr/src/supervisor/supervisor/dbus/udisks2/__init__.py:190> exception=DBusInterfaceMethodError('Object does not exist at path “/org/freedesktop/UDisks2/block_devices/sdb1”')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/dbus/udisks2/__init__.py", line 202, in _interfaces_added
    self._block_devices[object_path] = await UDisks2Block.new(
                                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/dbus/udisks2/block.py", line 78, in new
    await obj.connect(bus)
  File "/usr/src/supervisor/supervisor/dbus/udisks2/block.py", line 70, in connect
    await self._reload_interfaces()
  File "/usr/src/supervisor/supervisor/dbus/udisks2/block.py", line 242, in _reload_interfaces
    await self._partition.initialize(self.dbus)
  File "/usr/src/supervisor/supervisor/dbus/interface.py", line 108, in initialize
    await self.update()
  File "/usr/src/supervisor/supervisor/dbus/interface.py", line 128, in update
    self.properties = await self.dbus.get_properties(self.properties_interface)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/utils/dbus.py", line 221, in get_properties
    return await self.properties.call_get_all(interface)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/utils/dbus.py", line 122, in call_dbus
    raise DBus.from_dbus_error(err) from None
supervisor.exceptions.DBusInterfaceMethodError: Object does not exist at path “/org/freedesktop/UDisks2/block_devices/sdb1”
2024-09-14 21:47:13.669 WARNING (MainThread) [supervisor.hardware.monitor] Ignore device /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2 / failes to initialize by udev
2024-09-14 21:47:14.710 WARNING (MainThread) [supervisor.hardware.monitor] Ignore device /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2/2-2:1.0/host1/target1:0:0/1:0:0:0/bsg/1:0:0:0 / failes to initialize by udev
2024-09-14 21:47:14.789 WARNING (MainThread) [supervisor.hardware.monitor] Ignore device /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2/2-2:1.0/host1/target1:0:0/1:0:0:0/block/sdb / failes to initialize by udev
2024-09-14 21:47:14.791 WARNING (MainThread) [supervisor.hardware.monitor] Ignore device /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2/2-2:1.0/host1/target1:0:0/1:0:0:0/block/sdb/sdb1 / failes to initialize by udev
2024-09-14 21:47:14.793 WARNING (MainThread) [supervisor.hardware.monitor] Ignore device /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2/2-2:1.0/host1/target1:0:0/1:0:0:0/block/sdb/sdb2 / failes to initialize by udev
2024-09-14 21:47:32.428 WARNING (MainThread) [supervisor.hardware.monitor] Ignore device /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2 / failes to initialize by udev
2024-09-14 21:47:33.460 WARNING (MainThread) [supervisor.hardware.monitor] Ignore device /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2/2-2:1.0/host1/target1:0:0/1:0:0:0/bsg/1:0:0:0 / failes to initialize by udev
2024-09-14 21:47:33.538 WARNING (MainThread) [supervisor.hardware.monitor] Ignore device /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2/2-2:1.0/host1/target1:0:0/1:0:0:0/block/sdb / failes to initialize by udev
2024-09-14 21:47:33.539 WARNING (MainThread) [supervisor.hardware.monitor] Ignore device /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2/2-2:1.0/host1/target1:0:0/1:0:0:0/block/sdb/sdb1 / failes to initialize by udev
2024-09-14 21:47:33.539 WARNING (MainThread) [supervisor.hardware.monitor] Ignore device /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2/2-2:1.0/host1/target1:0:0/1:0:0:0/block/sdb/sdb2 / failes to initialize by udev
2024-09-14 21:47:43.710 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1892' coro=<UDisks2Manager._interfaces_added() done, defined at /usr/src/supervisor/supervisor/dbus/udisks2/__init__.py:190> exception=DBusInterfaceMethodError('Object does not exist at path “/org/freedesktop/UDisks2/drives/drive”')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/dbus/udisks2/__init__.py", line 208, in _interfaces_added
    self._drives[object_path] = await UDisks2Drive.new(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/dbus/udisks2/drive.py", line 47, in new
    await obj.connect(bus)
  File "/usr/src/supervisor/supervisor/dbus/interface.py", line 96, in connect
    await super().connect(bus)
  File "/usr/src/supervisor/supervisor/dbus/interface.py", line 50, in connect
    await self.initialize(await DBus.connect(bus, self.bus_name, self.object_path))
  File "/usr/src/supervisor/supervisor/dbus/interface.py", line 108, in initialize
    await self.update()
  File "/usr/src/supervisor/supervisor/dbus/interface.py", line 128, in update
    self.properties = await self.dbus.get_properties(self.properties_interface)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/utils/dbus.py", line 221, in get_properties
    return await self.properties.call_get_all(interface)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/utils/dbus.py", line 122, in call_dbus
    raise DBus.from_dbus_error(err) from None
supervisor.exceptions.DBusInterfaceMethodError: Object does not exist at path “/org/freedesktop/UDisks2/drives/drive”
2024-09-14 21:47:43.726 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1894' coro=<UDisks2Manager._interfaces_added() done, defined at /usr/src/supervisor/supervisor/dbus/udisks2/__init__.py:190> exception=DBusInterfaceError('D-Bus object /org/freedesktop/UDisks2/block_devices/sdb is not usable, introspection is missing required properties interface')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/dbus/udisks2/__init__.py", line 202, in _interfaces_added
    self._block_devices[object_path] = await UDisks2Block.new(
                                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/dbus/udisks2/block.py", line 78, in new
    await obj.connect(bus)
  File "/usr/src/supervisor/supervisor/dbus/udisks2/block.py", line 69, in connect
    await super().connect(bus)
  File "/usr/src/supervisor/supervisor/dbus/interface.py", line 96, in connect
    await super().connect(bus)
  File "/usr/src/supervisor/supervisor/dbus/interface.py", line 50, in connect
    await self.initialize(await DBus.connect(bus, self.bus_name, self.object_path))
  File "/usr/src/supervisor/supervisor/dbus/interface.py", line 104, in initialize
    raise DBusInterfaceError(
supervisor.exceptions.DBusInterfaceError: D-Bus object /org/freedesktop/UDisks2/block_devices/sdb is not usable, introspection is missing required properties interface
2024-09-14 21:47:48.187 WARNING (MainThread) [supervisor.hardware.monitor] Ignore device /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2 / failes to initialize by udev
2024-09-14 21:47:49.210 WARNING (MainThread) [supervisor.hardware.monitor] Ignore device /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2/2-2:1.0/host1/target1:0:0/1:0:0:0/bsg/1:0:0:0 / failes to initialize by udev
2024-09-14 21:47:49.598 WARNING (MainThread) [supervisor.hardware.monitor] Ignore device /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2/2-2:1.0/host1/target1:0:0/1:0:0:0/block/sdb / failes to initialize by udev
2024-09-14 21:48:03.596 WARNING (MainThread) [supervisor.hardware.monitor] Ignore device /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2 / failes to initialize by udev
2024-09-14 21:48:04.624 WARNING (MainThread) [supervisor.hardware.monitor] Ignore device /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2/2-2:1.0/host1/target1:0:0/1:0:0:0/bsg/1:0:0:0 / failes to initialize by udev
2024-09-14 21:48:05.020 WARNING (MainThread) [supervisor.hardware.monitor] Ignore device /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2/2-2:1.0/host1/target1:0:0/1:0:0:0/block/sdb / failes to initialize by udev
2024-09-14 21:48:15.105 INFO (MainThread) [supervisor.hardware.monitor] Detecting add hardware /dev/bus/usb/002/015 - None
2024-09-14 21:48:16.118 INFO (MainThread) [supervisor.hardware.monitor] Detecting add hardware /dev/bsg/1:0:0:0 - None
2024-09-14 21:48:16.187 INFO (MainThread) [supervisor.hardware.monitor] Detecting add hardware /dev/sdb - /dev/disk/by-id/ata-ST10000NM0046_ZA240NBA
2024-09-14 21:48:16.235 INFO (MainThread) [supervisor.hardware.monitor] Detecting add hardware /dev/sdb1 - /dev/disk/by-id/ata-ST10000NM0046_ZA240NBA-part1
2024-09-14 21:48:16.254 INFO (MainThread) [supervisor.hardware.monitor] Detecting add hardware /dev/sdb2 - /dev/disk/by-id/ata-ST10000NM0046_ZA240NBA-part2
2024-09-14 21:48:16.417 INFO (MainThread) [supervisor.docker.addon] Added cgroup permissions 'b 8:16 rwm' for device /dev/sdb to addon_db21ed7f_filebrowser
2024-09-14 21:48:16.585 INFO (MainThread) [supervisor.docker.addon] Added cgroup permissions 'b 8:17 rwm' for device /dev/sdb1 to addon_db21ed7f_filebrowser
2024-09-14 21:48:16.768 INFO (MainThread) [supervisor.docker.addon] Added cgroup permissions 'b 8:18 rwm' for device /dev/sdb2 to addon_db21ed7f_filebrowser
2024-09-14 21:48:17.909 INFO (MainThread) [supervisor.hardware.monitor] Detecting remove hardware /dev/bsg/1:0:0:0 - None
2024-09-14 21:48:17.918 INFO (MainThread) [supervisor.hardware.monitor] Detecting remove hardware /dev/sdb1 - /dev/disk/by-id/ata-ST10000NM0046_ZA240NBA-part1
2024-09-14 21:48:17.922 INFO (MainThread) [supervisor.hardware.monitor] Detecting remove hardware /dev/sdb2 - /dev/disk/by-id/ata-ST10000NM0046_ZA240NBA-part2
2024-09-14 21:48:17.936 INFO (MainThread) [supervisor.hardware.monitor] Detecting remove hardware /dev/sdb - /dev/disk/by-id/ata-ST10000NM0046_ZA240NBA
2024-09-14 21:48:18.020 INFO (MainThread) [supervisor.hardware.monitor] Detecting remove hardware /dev/bus/usb/002/015 - None

Any thoughts?

**Comment by dianlight** [comment]
It seems that usb connection is not stable. Sometime is a power problem, sometimes a cable problem rarely an hardware problem.

Did you try the hdd with a pc or Mac to exclude an hardware problem?

Do you have an external power source for the hdd? If not always use an external power source, rpi's usb are not able to supply full request power. If you don't have a power connector in your external hd use a usb hub with power.

Also if you connect the hd to usb3 ports ( the blue if I remember right ) you can try to change and connect to usb2 that are less power sensitive.

Another option is a cable problem, you can try to change the usb cable if you have another.

Another step is to configure the rip power sensor in ha if you don't yet do to monitor if the rpi has adequate power.

L.

**Comment by cristian19961** [comment]
Stupid. I tried another adapter on the Pi and now it's working. I just need a little finetuning, at the moment.
Is it possible to write to the external drive from another add-on? Like Sabnzbd?

**Comment by dianlight** [comment]
I don't know Sabnzbd but in your configuration you have enabled media library so if the addon can write to ha media simply select the media subfolder with the name of your disk and the game is done.

L.
